import { Globe, Flask, BookOpen, GraduationCap, Sun, Car } from "@/components/ui/Icons";

export interface Department {
  name: string;
  slug: string;
  descriptor: string;
  overview: string[];
  duration: string;
  level: string;
  intake: string;
  icon: React.ComponentType<{ size?: number; className?: string }>;
  subjects: string[];
  careers: string[];
  instructorName: string;
  instructorRole: string;
  instructorYears: number;
  instructorInitials: string;
  photos: string[];
}

export const departments: Department[] = [
  {
    name: "Heavy Machinery Operation & Maintenance",
    slug: "heavy-machinery-operation-maintenance",
    descriptor: "Operate and maintain heavy construction and mining equipment to industry standards",
    overview: [
      "The Heavy Machinery Operation & Maintenance programme trains students to safely and efficiently operate, inspect, and maintain heavy construction and mining equipment used across Rwanda's infrastructure and extractive industries.",
      "Students learn on real machines — excavators, wheel loaders, bulldozers, and compactors — progressing from classroom theory through hands-on simulation to supervised field operation. Every graduate leaves with the practical hours and certifications needed to step onto a job site from day one.",
      "This programme was designed in direct consultation with Rwanda's leading construction contractors, ensuring that the skills taught match exactly what employers demand. Our graduates are operating heavy equipment on national road projects, mining operations, and large-scale building sites across the country.",
    ],
    duration: "Short Course",
    level: "Certificate",
    intake: "Contact School",
    icon: GraduationCap,
    subjects: [
      "Equipment Safety & Regulations",
      "Hydraulic Systems",
      "Engine Maintenance",
      "Load Calculations",
      "Operational Procedures",
      "Pre-Shift Inspections",
      "Emergency Protocols",
      "Operator Certification Prep",
    ],
    careers: [
      "Equipment Operator",
      "Site Supervisor",
      "Plant Manager",
      "Maintenance Technician",
      "Heavy Equipment Inspector",
    ],
    instructorName: "Mr. Gaspard Niyitegeka",
    instructorRole: "Lead Instructor, Heavy Machinery",
    instructorYears: 14,
    instructorInitials: "GN",
    photos: [
      "/images/image1.png",
      "/images/image2.png",
      "/images/PeopleLookAtTrainingDevice.png",
      "/images/image4.jpg",
    ],
  },
  {
    name: "Solar Technology",
    slug: "solar-technology",
    descriptor: "Install, maintain, and commission solar PV systems for residential, commercial, and off-grid applications",
    overview: [
      "The Solar Technology programme equips students with the practical skills to design, install, commission, and maintain solar photovoltaic systems for residential, commercial, and off-grid applications across Rwanda and the wider East African region.",
      "Training covers the full solar project lifecycle — from site assessment and system sizing through panel mounting, inverter configuration, battery storage, and final commissioning. Students work with industry-standard equipment in our dedicated solar lab and on rooftop installations.",
      "With Rwanda's rapidly growing renewable energy sector, our graduates are in high demand. They are installing solar systems for homes, businesses, schools, and health centres — contributing directly to the country's clean energy goals while building rewarding careers.",
    ],
    duration: "Short Course",
    level: "Certificate",
    intake: "Contact School",
    icon: Sun,
    subjects: [
      "Solar PV Fundamentals",
      "System Sizing & Design",
      "Panel Installation Techniques",
      "Inverter & Battery Configuration",
      "Grid-Tie & Off-Grid Systems",
      "Electrical Safety for Solar",
      "Monitoring & Troubleshooting",
      "Commissioning & Handover",
    ],
    careers: [
      "Solar Installer",
      "Solar Technician",
      "Renewable Energy Technician",
      "Site Supervisor — Solar",
      "Maintenance Technician",
    ],
    instructorName: "Mr. Wang Lei",
    instructorRole: "Lead Instructor, Solar Technology",
    instructorYears: 12,
    instructorInitials: "WL",
    photos: [
      "/images/SolarPanelsTechnologyImage.png",
      "/images/image1.png",
      "/images/image2.png",
      "/images/PeopleLookAtTrainingDevice.png",
    ],
  },
  {
    name: "EV Cars",
    slug: "ev-cars",
    descriptor: "Diagnose, service, and maintain electric vehicles and their high-voltage systems",
    overview: [
      "The EV Cars programme prepares students for the rapidly emerging electric vehicle industry. Students learn to diagnose, service, and maintain electric vehicles and their complex high-voltage systems — skills that are increasingly essential as Rwanda and the world transition to electric mobility.",
      "The curriculum covers EV powertrain fundamentals, battery management systems, electric motor technology, charging infrastructure, and the specialist diagnostic tools and safety protocols required to work with high-voltage automotive systems.",
      "Our graduates are among the first EV-qualified technicians in Rwanda, positioning them at the forefront of a sector that is growing exponentially. They are servicing electric fleets, installing charging stations, and supporting the country's green transport ambitions.",
    ],
    duration: "Short Course",
    level: "Certificate",
    intake: "Contact School",
    icon: Car,
    subjects: [
      "EV Powertrain Fundamentals",
      "High-Voltage Battery Systems",
      "Electric Motor Technology",
      "Charging Infrastructure",
      "Diagnostic Tools & Software",
      "EV Safety Protocols",
      "Regenerative Braking Systems",
      "Vehicle Electronics & CAN Bus",
    ],
    careers: [
      "EV Technician",
      "Automotive Electrician",
      "EV Charging Installer",
      "Fleet Maintenance Technician",
      "Diagnostic Specialist",
    ],
    instructorName: "Mr. Li Jun",
    instructorRole: "Lead Instructor, EV Cars",
    instructorYears: 8,
    instructorInitials: "LJ",
    photos: [
      "/images/image1.png",
      "/images/PeopleLookAtTrainingDevice.png",
      "/images/image2.png",
      "/images/image4.jpg",
    ],
  },
  {
    name: "Land Surveying",
    slug: "land-surveying",
    descriptor: "Master the tools and techniques of modern land measurement, mapping, and GIS",
    overview: [
      "The Land Surveying programme trains students in the tools and techniques of modern land measurement, mapping, and geographic information systems (GIS). Graduates are qualified to conduct boundary surveys, topographic mapping, and cadastral work to national standards.",
      "Students progress from classroom theory — plane surveying, coordinate systems, and legal frameworks — through to hands-on fieldwork using total stations, GPS/GNSS receivers, and GIS software. Our dedicated surveying equipment and regular field exercises ensure that every student accumulates meaningful practical hours before graduation.",
      "Rwanda's growing construction, infrastructure, and land registration sectors create consistent demand for qualified surveyors. Our graduates are working with government land agencies, engineering firms, and construction companies across the country.",
    ],
    duration: "3 Years",
    level: "Level 3 – Level 5",
    intake: "Appointed by NESA",
    icon: Globe,
    subjects: [
      "Plane Surveying",
      "Total Station Operation",
      "GPS & GNSS Systems",
      "GIS Fundamentals",
      "Cadastral Surveying",
      "Topographic Mapping",
      "AutoCAD for Surveyors",
      "Legal Framework for Land",
    ],
    careers: [
      "Land Surveyor",
      "GIS Analyst",
      "Cadastral Officer",
      "Site Engineer",
      "Mapping Technician",
      "Urban Planner Support",
    ],
    instructorName: "Ms. Yvette Mukamugema",
    instructorRole: "Lead Instructor, Land Surveying",
    instructorYears: 11,
    instructorInitials: "YM",
    photos: [
      "/images/LandSurveyingLecturer.jpg",
      "/images/image1.png",
      "/images/image2.png",
      "/images/PeopleLookAtTrainingDevice.png",
    ],
  },
  {
    name: "Electrical Technology",
    slug: "electrical-technology",
    descriptor: "Design, install, and maintain industrial electrical systems to national safety codes",
    overview: [
      "The Electrical Technology programme produces qualified electricians and electrical technicians who can design, install, test, and maintain electrical systems in residential, commercial, and industrial settings — all to Rwanda's national electrical safety codes.",
      "Students learn AC/DC circuit theory, electrical wiring standards, motor control systems, PLC programming, industrial panel building, fault diagnosis, and solar PV installation. Our electrical lab mirrors real industrial environments, giving students hands-on experience with the exact equipment they will use in their careers.",
      "Electricians and electrical technicians are among the most consistently demanded trades in Rwanda. Our graduates work in construction, manufacturing, energy, and facilities management — with many progressing to supervisory and engineering support roles within a few years of graduating.",
    ],
    duration: "3 Years",
    level: "Level 3 – Level 5",
    intake: "Appointed by NESA",
    icon: Flask,
    subjects: [
      "AC/DC Circuit Theory",
      "Electrical Wiring Standards",
      "Motor Control Systems",
      "PLC Programming Basics",
      "Solar PV Installation",
      "Industrial Panel Building",
      "Fault Diagnosis",
      "Rwanda Electrical Codes",
    ],
    careers: [
      "Electrician",
      "Electrical Technician",
      "PLC Programmer",
      "Solar Installer",
      "Panel Builder",
      "Maintenance Engineer",
    ],
    instructorName: "Mr. Théodore Nsengiyumva",
    instructorRole: "Lead Instructor, Electrical Technology",
    instructorYears: 16,
    instructorInitials: "TN",
    photos: [
      "/images/image2(ElecticalControlCabinate).png",
      "/images/image1.png",
      "/images/PeopleLookAtTrainingDevice.png",
      "/images/image2.png",
    ],
  },
  {
    name: "Public Works",
    slug: "public-works",
    descriptor: "Plan, construct, and supervise road and civil infrastructure projects from base to finish",
    overview: [
      "The Public Works programme trains students to plan, construct, and supervise road and civil infrastructure projects — from earthworks and drainage through to bituminous surfacing and quality control testing.",
      "Students study road design fundamentals, soil mechanics, construction materials, road geometry, drainage systems, compaction and paving techniques, and construction project management. Practical training takes place both in our labs and on supervised field visits to active construction sites.",
      "Rwanda's ambitious infrastructure development programme — including national road networks, urban development, and rural connectivity projects — creates strong and sustained demand for qualified public works technicians. Our graduates are working on some of the country's most significant infrastructure projects.",
    ],
    duration: "3 Years",
    level: "Level 3 – Level 5",
    intake: "Appointed by NESA",
    icon: BookOpen,
    subjects: [
      "Road Design Fundamentals",
      "Soil Mechanics",
      "Bituminous Materials",
      "Road Geometry",
      "Drainage Systems",
      "Quality Control Testing",
      "Compaction & Paving",
      "Construction Project Management",
    ],
    careers: [
      "Road Construction Technician",
      "Site Supervisor",
      "Quality Control Inspector",
      "Civil Works Foreman",
      "Road Safety Auditor",
    ],
    instructorName: "Mr. Innocent Habimana",
    instructorRole: "Lead Instructor, Public Works",
    instructorYears: 13,
    instructorInitials: "IH",
    photos: [
      "/images/image4.jpg",
      "/images/image1.png",
      "/images/PeopleLookAtTrainingDevice.png",
      "/images/image2.png",
    ],
  },
  {
    name: "Computer Systems & Architecture",
    slug: "computer-systems-architecture",
    descriptor: "Build, maintain, and troubleshoot computer hardware and network infrastructure",
    overview: [
      "The Computer Systems & Architecture programme trains students to build, maintain, troubleshoot, and secure computer hardware and network infrastructure — the backbone of every modern organisation.",
      "The curriculum covers computer architecture, network fundamentals, operating systems, hardware troubleshooting, structured cabling, cybersecurity basics, database introduction, and cloud computing essentials. Students gain hands-on experience in our dedicated IT lab, working with real servers, networking equipment, and enterprise software.",
      "As Rwanda positions itself as a regional technology hub, qualified IT technicians, network engineers, and systems administrators are in growing demand across every sector — from government and banking to telecommunications and tech startups. Our graduates are building and maintaining the digital infrastructure that powers Rwanda's development.",
    ],
    duration: "3 Years",
    level: "Level 3 – Level 5",
    intake: "Appointed by NESA",
    icon: GraduationCap,
    subjects: [
      "Computer Architecture",
      "Network Fundamentals",
      "Operating Systems",
      "Hardware Troubleshooting",
      "Structured Cabling",
      "Cybersecurity Basics",
      "Database Introduction",
      "Cloud Computing Essentials",
    ],
    careers: [
      "IT Technician",
      "Network Engineer",
      "Systems Administrator",
      "Hardware Specialist",
      "Help Desk Analyst",
      "IT Support Officer",
    ],
    instructorName: "Ms. Clarisse Umurerwa",
    instructorRole: "Lead Instructor, Computer Systems & Architecture",
    instructorYears: 9,
    instructorInitials: "CU",
    photos: [
      "/images/image1.png",
      "/images/image2.png",
      "/images/PeopleLookAtTrainingDevice.png",
      "/images/image4.jpg",
    ],
  },
];
