export type EventCategory = "Academic" | "Ceremony" | "Competition" | "Social" | "Career";

export interface CalendarEvent {
  slug: string;
  title: string;
  date: Date;
  dateStr: string; // e.g. "January 5, 2026"
  time: string;
  location: string;
  category: EventCategory;
  description: string;
  open: boolean;
  body: string[];
}

export const categoryStyles: Record<EventCategory, string> = {
  Academic:    "bg-blue-100 text-blue-700",
  Ceremony:    "bg-amber-100 text-amber-700",
  Competition: "bg-red-100 text-red-700",
  Social:      "bg-green-100 text-green-700",
  Career:      "bg-purple-100 text-purple-700",
};

export const events: CalendarEvent[] = [
  {
    slug: "orientation-day-2026",
    title: "Orientation Day",
    date: new Date("2026-01-05"),
    dateStr: "January 5, 2026",
    time: "8:00 AM",
    location: "Main Hall",
    category: "Ceremony",
    description: "Welcoming ceremony for Intake 1 students and families.",
    open: true,
    body: [
      "Orientation Day marks the official beginning of the academic year at Forever Tvet Institute. The day is designed to help new students transition from the application process into active student life, and to give families a clear picture of what the year ahead will involve.",
      "The morning begins with a formal welcome ceremony in the Main Hall. The Headmaster opens proceedings with an address covering the school's mission, values, and expectations. The Head Parent, representing the Parent Committee, also addresses the gathering and introduces the communication structures available to families throughout the year.",
      "Following the formal ceremony, students divide into programme groups for introductory sessions with their lead instructors. Each group receives a full walkthrough of their curriculum structure, timetable, assessment schedule, and the practical facilities they will use. Safety briefings are delivered for all programmes with practical components.",
      "The afternoon includes a guided campus tour led by returning students who serve as informal peer guides. New students have the opportunity to ask questions, familiarise themselves with the campus, and begin forming connections with their cohort.",
      "Orientation Day is open to students and their families. There is no cost to attend beyond standard transport to campus. Students who are unable to attend the morning ceremony due to travel distance may arrive for the afternoon session, but are encouraged to contact the Dean of Students in advance.",
    ],
  },
  {
    slug: "industrial-safety-workshop",
    title: "Industrial Safety Workshop",
    date: new Date("2026-01-12"),
    dateStr: "January 12, 2026",
    time: "9:00 AM – 12:00 PM",
    location: "Simulation Lab",
    category: "Academic",
    description: "Mandatory health and safety briefing for all practical programs.",
    open: false,
    body: [
      "The Industrial Safety Workshop is a mandatory half-day session delivered to all students enrolled in practical programmes at Forever Tvet Institute. Completion of this workshop is a prerequisite for participation in any lab, workshop, or field activity during the academic year.",
      "The session covers the legal and regulatory framework for workplace health and safety in Rwanda, with a focus on the specific hazards present in each programme area — including electrical systems, heavy machinery, surveying equipment, and public works environments. Students are taught to identify risks, apply appropriate protective measures, and respond to common workplace incidents.",
      "Practical demonstration forms a significant part of the workshop. Students rotate through stations covering correct use of personal protective equipment (PPE), fire extinguisher operation, first aid priorities, and safe equipment shutdown procedures. Instructors assess student understanding through brief practical checks at each station.",
      "A short written component at the end of the session tests retention of the key regulatory and procedural content. Students who do not achieve the required standard are given the opportunity to resit the assessment within five working days. The workshop is delivered by the school's qualified health and safety officer in partnership with programme instructors.",
      "This session is restricted to enrolled students. Parents and visitors are not permitted in the Simulation Lab during active safety training. Students should arrive wearing appropriate footwear and should not bring valuables to the session.",
    ],
  },
  {
    slug: "guest-lecture-renewable-energy",
    title: "Guest Lecture: Renewable Energy in Rwanda",
    date: new Date("2026-01-26"),
    dateStr: "January 26, 2026",
    time: "2:00 PM",
    location: "Lecture Hall",
    category: "Academic",
    description: "Industry expert talk on the growth of renewables in East Africa.",
    open: true,
    body: [
      "Forever Tvet Institute's guest lecture series continues with a talk on renewable energy development across Rwanda and the wider East African region. The speaker for this session is a senior engineer with direct experience in the planning, installation, and commissioning of large-scale solar projects in Rwanda.",

      "The lecture will cover the current state of Rwanda's energy mix, the country's national targets for renewable capacity expansion, and what the growth trajectory means for the demand for qualified TVET graduates in the electricity and solar sectors. Students will gain insight into the scale and pace of change in an industry they may enter within months of graduating.",
      "A substantial portion of the session is dedicated to the career dimension. The speaker will discuss the specific technical skills that employers are actively looking for, how salaries in the sector have evolved over the past five years, and the pathways available to graduates who want to advance from installation roles into supervisory or design positions.",
      "The session is open to the public, and prospective students interested in the Electrical Technology programme are encouraged to attend. Current students from all programmes are welcome. The lecture runs for approximately 60 minutes, followed by a 20-minute open Q&A.",
      "No registration is required for this event. Seats are available on a first-come, first-served basis. The Lecture Hall accommodates up to 80 attendees. For groups of five or more, please email events@forevertvet.rw in advance so adequate seating can be arranged.",
    ],
  },
  {
    slug: "inter-program-coding-challenge",
    title: "Inter-Program Coding Challenge",
    date: new Date("2026-02-14"),
    dateStr: "February 14, 2026",
    time: "9:00 AM",
    location: "Computer Lab",
    category: "Competition",
    description: "Students from all programs compete in a timed coding challenge.",
    open: false,
    body: [
      "The Inter-Program Coding Challenge is an annual competition open to all Forever Tvet Institute students, regardless of programme. The event is designed to promote computational thinking and problem-solving skills across disciplines — recognising that digital literacy and logic-based reasoning are relevant beyond the Computer Systems & Architecture programme.",
      "The competition runs in two rounds. The first round is a timed individual challenge, where students tackle a set of structured problems covering basic programming logic, data manipulation, and algorithm design. Problems are presented in a way that does not disadvantage students from non-computing backgrounds, though Computer Systems & Architecture students are expected to perform at a higher level on the advanced questions.",
      "The top 10 individual scorers from round one advance to the team round in the afternoon, where they are grouped into pairs to tackle a more complex, open-ended problem. The team round is assessed on both correctness and the clarity of the solution — reflecting real-world expectations that code should be readable and maintainable, not just functional.",
      "Prizes are awarded to the top three finishing individuals and the winning team. Past winners have gone on to represent the school at national-level competitions and have used their challenge performance as evidence of competency during internship interviews.",
      "Participation is capped at 40 students due to the computer lab capacity. Registration closes three days before the event. Students should register via the Dean of Students office. Latecomers will not be permitted entry once the first round timer has started.",
    ],
  },
  {
    slug: "career-fair-employer-open-day",
    title: "Career Fair — Employer Open Day",
    date: new Date("2026-02-28"),
    dateStr: "February 28, 2026",
    time: "9:00 AM – 3:00 PM",
    location: "Main Hall",
    category: "Career",
    description: "Meet 20+ employers recruiting for internships and graduate roles.",
    open: true,
    body: [
      "The annual Career Fair is one of the most important events in the Forever Tvet Institute calendar. Each year, the school hosts employers from across the sectors represented in its programmes — construction, electrical technology, IT and networking, land surveying, and public works — giving current students and recent graduates direct access to recruiters and hiring managers.",
      "This year's event brings together more than 20 confirmed employers. Represented companies include active infrastructure contractors, solar installation firms, IT service providers, and engineering consultancies. Each employer maintains a stand in the Main Hall for the duration of the day and conducts informal conversations, accepts CV submissions, and in some cases carries out brief screening interviews on the spot.",
      "The morning is reserved for current Intake 1 students, who are allocated specific time slots to visit employer stands as a structured part of their programme timetable. The afternoon session is open to the public, including Intake 2 applicants, prospective students, and recent graduates seeking employment or a change of employer.",
      "At last year's Career Fair, six employers extended conditional offers of internship placement or expressed strong hiring intent before leaving campus. Three Electrical Technology students received verbal internship offers ahead of the school's formal placement schedule.",
      "A panel discussion is scheduled for 1:00 PM. Four industry professionals — all graduates of vocational training programmes — will discuss career progression, salary benchmarks, and what employers look for when hiring TVET graduates. The panel is open to all attendees and includes a moderated Q&A session.",
      "Students wishing to make the most of the day are encouraged to prepare a concise CV in advance. The Dean of Students office can assist with CV review in the week before the event. Walk-ins are welcome for the afternoon session, but students should carry at least five printed CV copies.",
    ],
  },
  {
    slug: "cultural-day-student-showcase",
    title: "Cultural Day & Student Showcase",
    date: new Date("2026-03-14"),
    dateStr: "March 14, 2026",
    time: "10:00 AM",
    location: "Campus Grounds",
    category: "Social",
    description: "Celebrating the diversity of our student community with performances, food, and student projects.",
    open: true,
    body: [
      "Cultural Day is Forever Tvet Institute's annual celebration of the diversity of its student community. The event takes place across the campus grounds and combines student performances, a food fair, a practical project showcase, and community activities into a full-day programme.",
      "The morning begins with the student project showcase, where teams from each programme display work completed during Phase 1. Computer Systems & Architecture students demonstrate working applications and network setups. Electrical Technology students exhibit wiring boards and solar panel configurations. Land Surveying students present field maps produced during their outdoor sessions. The showcase is open to visitors throughout the day and gives families and prospective students a first-hand look at the standard of practical work produced at the school.",
      "Performances begin at midday. Students from across the intake perform music, spoken word, and dance representing their home provinces and cultural backgrounds. The stage is open to all students — no prior arrangement is required, and spontaneous participation is welcome.",
      "The food fair runs from 11:00 AM to 2:00 PM. Students and staff contribute dishes representing cuisines from across Rwanda and the region. All food is available by donation, with proceeds going to the student welfare fund.",
      "Cultural Day is fully open to the public. Families, prospective students, community members, and alumni are all warmly invited. There is no entrance fee. The event typically concludes between 3:00 PM and 4:00 PM, depending on performance scheduling.",
    ],
  },
  {
    slug: "phase-2-commencement",
    title: "Phase 2 Commencement",
    date: new Date("2026-03-23"),
    dateStr: "March 23, 2026",
    time: "9:00 AM",
    location: "Main Hall",
    category: "Ceremony",
    description: "Marking the transition of Intake 1 students into Phase 2 of their programs.",
    open: false,
    body: [
      "The Phase 2 Commencement ceremony marks a significant transition in the academic journey of Intake 1 students at Forever Tvet Institute. Having completed Phase 1 — which covers foundational theory, safety protocols, and introductory practical skills — students formally move into Phase 2, where the depth and complexity of both theoretical and practical work increases substantially.",
      "The ceremony opens with a brief address from the Headmaster, reflecting on what Phase 1 has demanded and what Phase 2 will require. Lead instructors for each programme also speak, giving students a preview of the Phase 2 curriculum and the key competencies they will be expected to develop.",
      "A significant element of the Phase 2 transition is the allocation of advanced equipment access. Students who have demonstrated appropriate safety awareness and foundational skill during Phase 1 are cleared for unsupervised access to specific equipment and lab areas. This clearance is confirmed formally during the ceremony.",
      "The Dean of Students uses the event to discuss the academic expectations for Phase 2, including assessment frequency, attendance thresholds, and the criteria for Phase 2 completion and progression to the Phase 3 internship placement.",
      "The ceremony is a school-internal event and is not open to the public or families. However, the school sends a written summary of Phase 2 commencement outcomes to all registered parents via the Parent Committee communication channels. Students with any Phase 1 outstanding work or assessment results are notified individually before the ceremony date.",
    ],
  },
  {
    slug: "land-survey-field-trip",
    title: "Land Surveying Field Trip",
    date: new Date("2026-04-04"),
    dateStr: "April 4, 2026",
    time: "All Day",
    location: "Off-Campus Field Site",
    category: "Academic",
    description: "Land Surveying students conduct a full-day practical field exercise.",
    open: false,
    body: [
      "The Land Surveying Field Trip is a full-day off-campus exercise for students enrolled in the Land Surveying programme. The trip forms part of the Phase 2 curriculum and directly contributes to assessment outcomes for both the practical field competency unit and the documentation and reporting unit.",
      "Students travel to a designated field site that presents realistic surveying conditions: irregular terrain, varied vegetation, and a defined boundary that requires both GPS-based and total station measurement to accurately record. The exercise mirrors the conditions students are likely to encounter on professional assignments following graduation.",
      "The day is structured around three main tasks: an initial site reconnaissance and planning session led by the programme instructor; a supervised measurement phase where student pairs independently operate total stations, GPS receivers, and field documentation tools; and a final data compilation session where raw measurements are checked, errors are discussed, and initial plans are drafted on-site.",
      "Students are expected to produce a complete field record by the end of the day. Formal reports based on the trip data are submitted within one week of return and are graded as part of the Phase 2 assessment schedule.",
      "The field trip is an enrolled-students-only exercise. Students must arrive at the school transport departure point by 7:30 AM. Appropriate footwear, sun protection, and sufficient water for the day are required. A full kit list is distributed to students two weeks before the trip date.",
    ],
  },
  {
    slug: "alumni-networking-evening",
    title: "Alumni Networking Evening",
    date: new Date("2026-04-25"),
    dateStr: "April 25, 2026",
    time: "4:00 PM – 7:00 PM",
    location: "Student Common Room",
    category: "Career",
    description: "Graduates and current students connect over career stories and opportunities.",
    open: false,
    body: [
      "The Alumni Networking Evening brings together graduates of Forever Tvet Institute and current students in an informal setting designed to facilitate genuine career conversations. Unlike the structured Career Fair, this event is intimate and conversational — giving students the opportunity to ask candid questions of people who have recently navigated the same transition they are approaching.",
      "Alumni attending this event represent a range of programme backgrounds and employment stages: some are in their first year of employment, others have moved into supervisory roles, and a small number have started their own businesses. This range of experience allows students to understand what early career progression looks like across different industries.",
      "The evening runs in an open-floor format with no formal presentations. Alumni circulate freely, and students are encouraged to approach anyone they find relevant to their own career interests. Light refreshments are provided. The school's placement team is also present and available to discuss internship placement status and post-graduation support.",
      "Participation for current students is by registration only, as the Common Room capacity limits attendance to 60 people. Priority is given to Phase 2 students who are approaching their internship placement period, as the event is most immediately useful for those closest to leaving formal study.",
      "Alumni who wish to attend the evening or register for the alumni network should contact the Dean of Students office or visit the Alumni section of the school website. Participation is free and open to all Forever Tvet graduates.",
    ],
  },
  {
    slug: "internship-launch-day",
    title: "Internship Launch Day",
    date: new Date("2026-05-18"),
    dateStr: "May 18, 2026",
    time: "9:00 AM",
    location: "Main Hall",
    category: "Ceremony",
    description: "Formal send-off for students beginning their industry internship placements.",
    open: false,
    body: [
      "Internship Launch Day is the formal ceremony marking the beginning of Phase 3 for Intake 1 students — the industry internship placement that forms the final and most significant practical component of their programme.",
      "By the time students attend Internship Launch Day, their placements have already been confirmed by the school's industry placement team. Each student enters the ceremony knowing which company they will join, in what role, and on what start date. The ceremony is therefore less about logistics and more about the transition in mindset that the internship requires.",
      "The Headmaster addresses all students, setting out expectations for professional conduct, communication with host employers, and reporting obligations to the school during the placement period. Lead instructors from each programme also speak briefly, summarising the technical competencies students should aim to demonstrate during their placement.",
      "Students are paired with a school-based mentor for the duration of their internship. Mentors check in with students monthly and serve as the first point of contact if any issue arises with the host employer. Mentor assignments are announced during the ceremony.",
      "Internship Launch Day is an enrolled-students-only event. However, the school issues a written placement confirmation to each student's registered family contact on the same day, confirming the employer name, role, start date, and monthly stipend (where applicable). Students whose placements have not yet been confirmed by this date are seen individually by the placement team and assigned as soon as a match is identified.",
    ],
  },
  {
    slug: "national-tvet-day-celebration",
    title: "National TVET Day Celebration",
    date: new Date("2026-05-30"),
    dateStr: "May 30, 2026",
    time: "All Day",
    location: "Campus Grounds",
    category: "Ceremony",
    description: "Forever Tvet joins institutions across Rwanda in celebrating vocational education.",
    open: true,
    body: [
      "National TVET Day is observed annually across Rwanda as a recognition of the role vocational and technical education plays in the country's economic development. Forever Tvet Institute participates fully in the national celebration, hosting a campus-wide programme that is open to the public.",
      "The day's programme includes demonstration sessions in each of the school's practical training areas. Visitors are guided through the Heavy Machinery yard, the Solar Technology outdoor facility, the Computer Systems lab, the Electrical Technology workshops, and the Land Surveying field area. Instructors and students explain what they are working on and demonstrate equipment operation.",
      "A formal address in the morning acknowledges the contribution of Rwanda's TVET sector to national workforce development. The event aligns with WDA communications and may include a video message or representative from the Rwanda Workforce Development Authority.",
      "The day also serves as an informal open day for prospective students and families who are considering applying for the next intake. Admissions staff are available throughout the day to answer questions, explain programme requirements, and assist with application queries. Previous graduates are often present as informal ambassadors.",
      "National TVET Day is fully open to the public at no cost. Visitors do not need to register in advance. Groups of ten or more (e.g., schools, community organisations) are asked to notify the school in advance so that guide availability can be planned. Contact events@forevertvet.rw for group visits.",
    ],
  },
  {
    slug: "graduation-ceremony-intake-1",
    title: "Graduation Ceremony — Intake 1",
    date: new Date("2026-07-31"),
    dateStr: "July 31, 2026",
    time: "10:00 AM",
    location: "Main Hall",
    category: "Ceremony",
    description: "Certificate presentation for all Intake 1 graduates. Families warmly welcome.",
    open: true,
    body: [
      "The Graduation Ceremony is the most significant event in the Forever Tvet Institute calendar — the moment when students who have completed all programme requirements, passed their national RQF examinations, and fulfilled their internship placement obligations receive their official certificates.",
      "The ceremony is held in the Main Hall and is attended by graduates, their families, school administration and faculty, industry partners, and representatives from the Rwanda Workforce Development Authority. The Main Hall is arranged for the full guest list, and families are warmly encouraged to attend. There is no limit on the number of family members per graduate.",
      "The morning begins with a formal procession. The Headmaster delivers the commencement address, reflecting on the cohort's journey and acknowledging the specific achievements of the intake. Programme instructors present certificates to graduates individually, with each graduate's name, programme, and any distinctions announced as they receive their award.",
      "Following the certificate presentation, several special awards are presented. These include the Top Graduate award for each programme (based on combined examination and practical performance), the Employer Commendation award (given to a graduate whose internship host employer submitted an exceptional evaluation), and the Community Contribution award (determined by peer and instructor nomination).",
      "A reception follows the formal ceremony and is open to all graduates, families, and guests. Industry partners who attended the event are present at the reception and frequently use the occasion for informal hiring conversations with graduates whose records they have reviewed in advance.",
      "Families who require assistance with transport arrangements for the graduation day should contact the Dean of Students office at least two weeks in advance. The school can provide information on recommended transport options from different parts of Rwanda.",
    ],
  },
];
